
package victor.training.ws.responsibility.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ResponsibilityWS_v1", targetNamespace = "http://training.victor/ws/responsibility/v1", wsdlLocation = "file:/D:/workspace/training/webservices/src/wsdl/responsibility.v1.wsdl")
public class ResponsibilityWSV1
    extends Service
{

    private final static URL RESPONSIBILITYWSV1_WSDL_LOCATION;
    private final static WebServiceException RESPONSIBILITYWSV1_EXCEPTION;
    private final static QName RESPONSIBILITYWSV1_QNAME = new QName("http://training.victor/ws/responsibility/v1", "ResponsibilityWS_v1");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/workspace/training/webservices/src/wsdl/responsibility.v1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RESPONSIBILITYWSV1_WSDL_LOCATION = url;
        RESPONSIBILITYWSV1_EXCEPTION = e;
    }

    public ResponsibilityWSV1() {
        super(__getWsdlLocation(), RESPONSIBILITYWSV1_QNAME);
    }

    public ResponsibilityWSV1(WebServiceFeature... features) {
        super(__getWsdlLocation(), RESPONSIBILITYWSV1_QNAME, features);
    }

    public ResponsibilityWSV1(URL wsdlLocation) {
        super(wsdlLocation, RESPONSIBILITYWSV1_QNAME);
    }

    public ResponsibilityWSV1(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RESPONSIBILITYWSV1_QNAME, features);
    }

    public ResponsibilityWSV1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ResponsibilityWSV1(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ResponsibilitySEI
     */
    @WebEndpoint(name = "SoapPort")
    public ResponsibilitySEI getSoapPort() {
        return super.getPort(new QName("http://training.victor/ws/responsibility/v1", "SoapPort"), ResponsibilitySEI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ResponsibilitySEI
     */
    @WebEndpoint(name = "SoapPort")
    public ResponsibilitySEI getSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://training.victor/ws/responsibility/v1", "SoapPort"), ResponsibilitySEI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RESPONSIBILITYWSV1_EXCEPTION!= null) {
            throw RESPONSIBILITYWSV1_EXCEPTION;
        }
        return RESPONSIBILITYWSV1_WSDL_LOCATION;
    }

}
